#include <pebble.h>
#pragma once

#define NOZERO(s) ((*s == '0')?(s+1):s)

typedef enum {
  KEY_FONT = 0,
  KEY_COLOR_BG,
  KEY_COLOR_DATE,
  KEY_COLOR_TIME,
  KEY_LAST
} MessageKey;

enum {
  FONT_HELVETICA = 0,
  FONT_AVERIA,
  FONT_UBUNTU,
  FONT_LAST
};

const int fonts[FONT_LAST][2] = {
#ifdef PBL_RECT
  {RESOURCE_ID_FONT_HELVETICA_R_28, RESOURCE_ID_FONT_HELVETICA_B_48},
  {RESOURCE_ID_FONT_AVERIA_R_28, RESOURCE_ID_FONT_AVERIA_B_48},
  {RESOURCE_ID_FONT_UBUNTU_R_28, RESOURCE_ID_FONT_UBUNTU_B_48}
#else
  {RESOURCE_ID_FONT_HELVETICA_R_28, RESOURCE_ID_FONT_HELVETICA_B_64},
  {RESOURCE_ID_FONT_AVERIA_R_28, RESOURCE_ID_FONT_AVERIA_B_64},
  {RESOURCE_ID_FONT_UBUNTU_R_28, RESOURCE_ID_FONT_UBUNTU_B_64}
  #endif
};
